name: Cron Alertas Empleo

on:
  schedule:
    # Se ejecuta todos los días a las 08:00 y a las 15:00 UTC
    - cron: '0 8,15 * * *'
  workflow_dispatch: # Permite ejecutar el workflow manualmente

jobs:
  scraping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Instalar dependencias de Node
        run: npm install

      - name: Instalar dependencias del sistema y Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Ejecutar orquestador de ofertas
        env:
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
        run: node obtenerMultiples.js
