name: Obtener ofertas de empleo

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"   # cada 30 min

jobs:
  ejecutar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar script
        run: node obtenerMultiples.js
